# serverless.yml

service: iConsent

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'
    - env/**
    - code.zip
    - .dockerignore
    - .gitignore
    - Dockerfile
    - LICENSE
    - package.json
    - package-lock.json
    - README.md
    - serverless.yaml

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-2
  timeout: 15
  role: arn:aws:iam::699850692529:role/lambda-s3-role

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: POST video
    layers:
      - arn:aws:lambda:us-west-2:699850692529:layer:code:1
      - arn:aws:lambda:us-west-2:699850692529:layer:weasyprint:1
