# serverless.yml

service: iConsent

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'
    - env/**
    - code.zip
    - .dockerignore
    - .gitignore
    - Dockerfile
    - input.json
    - LICENSE
    - package.json
    - package-lock.json
    - README.md
    - serverless.yaml

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-2

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

layers:
  layerOne:
    package:
      artifact: code.zip