# serverless.yml

service: iConsent

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'
    - package.json
    - package-lock.json
    - flask-app/**
    - serverless.yaml

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  memorySize: 512
  timeout: 28
  role: arn:aws:iam::699850692529:role/lambda-s3-role

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: video
          method: post
          cors: true
      - http:
          path: dashboard
          method: post
          cors:
            origin: '*'
            headers:
              - sessionId
              - language
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
      - http:
          path: consent
          method: post
          cors:
            origin: '*'
            headers:
              - consentArtefactId
              - fiu
              - language
              - sessionId
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    layers:
      - arn:aws:lambda:ap-south-1:699850692529:layer:iconsent-dependency-layer:1